version: "3"
services:
  web:
    build: ./web
    image: web:latest
    ports:
      - "80:80"
    links:
      - teamcity-server
  teamcity-server:
    image: jetbrains/teamcity-server
    ports:
      - "8111:8111"
  teamcity-agent:
    image: jetbrains/teamcity-agent
    links:
      - teamcity-server
    environment:
      - SERVER_URL=http://teamcity-server:8111

