version: "3"
services:
  teamcity-server:
    image: jetbrains/teamcity-server
    ports:
      - "8111:8111"
    restart: always
  teamcity-agent:
    build: ./teamcity-agent
    image: teamcity-agent:latest
    links:
      - teamcity-server
    environment:
      - SERVER_URL=http://teamcity-server:8111
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always