version: "3"
services:
  ssl-proxy:
    build: ./ssl-proxy
    image: ssl-proxy:latest
    extra_hosts:
      - "dockerhost:172.17.0.1"
    restart: always
    environment:
      - CERTBOT_EMAIL=russ.frisch@gmail.com
    ports:
      - 80:80
      - 443:443
  teamcity-server:
    image: jetbrains/teamcity-server
    ports:
      - 127.0.0.1:8111:8111
    restart: always
  teamcity-agent:
    build: ./teamcity-agent
    image: teamcity-agent:latest
    links:
      - teamcity-server
    environment:
      - SERVER_URL=http://teamcity-server:8111
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
  registry:
    image: registry:2
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - ./data:/var/lib/registry
    restart: always